In [31]:
!pip install tensorflow version == 2.10.0

ERROR: Invalid requirement: '=='


In [3]:
from tensorflow.keras.preprocessing.text import one_hot

In [5]:
##sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [7]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [9]:
### Vocabulary size
voc_size=10000

### One-hot Representation

In [12]:
ohr = [one_hot(words, voc_size)for words in sent]
print(ohr)

[[7620, 5311, 3156, 2004], [7620, 5311, 3156, 1909], [7620, 2417, 3156, 6051], [1042, 2744, 71, 8547, 2247], [1042, 2744, 71, 8547, 8374], [190, 7620, 7360, 3156, 7190], [834, 4472, 9152, 8547]]


### Word Embedding Representation

In [15]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [17]:
## pre padding
sent_length=8
embedded_docs=pad_sequences(ohr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 7620 5311 3156 2004]
 [   0    0    0    0 7620 5311 3156 1909]
 [   0    0    0    0 7620 2417 3156 6051]
 [   0    0    0 1042 2744   71 8547 2247]
 [   0    0    0 1042 2744   71 8547 8374]
 [   0    0    0  190 7620 7360 3156 7190]
 [   0    0    0    0  834 4472 9152 8547]]


In [19]:
## 10 feature dimesnions
dim=10

In [21]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

C:\Users\DELL\anaconda3\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [23]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [27]:
import tensorflow as tf
print(tf.__version__)

2.17.0


In [33]:
model.predict(embedded_docs[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 454ms/step


array([[ 0.00494859, -0.04307863, -0.0351752 ,  0.01738825, -0.04587597,
         0.01079106,  0.01789229,  0.00396239,  0.04020325, -0.04256265],
       [ 0.00494859, -0.04307863, -0.0351752 ,  0.01738825, -0.04587597,
         0.01079106,  0.01789229,  0.00396239,  0.04020325, -0.04256265],
       [ 0.00494859, -0.04307863, -0.0351752 ,  0.01738825, -0.04587597,
         0.01079106,  0.01789229,  0.00396239,  0.04020325, -0.04256265],
       [ 0.00494859, -0.04307863, -0.0351752 ,  0.01738825, -0.04587597,
         0.01079106,  0.01789229,  0.00396239,  0.04020325, -0.04256265],
       [ 0.04070411,  0.00613087,  0.02172938, -0.00259454, -0.00675495,
         0.00874015, -0.00730294,  0.03716309, -0.01679578,  0.02244094],
       [ 0.01059213,  0.01554466, -0.03684279,  0.02848596, -0.03368232,
        -0.0217177 ,  0.02199711, -0.03014733,  0.00417859,  0.00040026],
       [-0.00080581,  0.01853007,  0.03574804, -0.03347786, -0.0280436 ,
         0.00040613, -0.02740881,  0.02399831

In [37]:
print(model.predict(embedded_docs))

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None

In [39]:
## Assighment
sent = ["The world is a better place",
        "Marvel series is my favourite movie",
        "I like DC movies",
        "The cat is eating the food",
       "Tom and Jerry is my favourite movie",
        "Python is my favourite programming language"]

In [41]:
sent

['The world is a better place',
 'Marvel series is my favourite movie',
 'I like DC movies',
 'The cat is eating the food',
 'Tom and Jerry is my favourite movie',
 'Python is my favourite programming language']

In [43]:
voc_size = 5000

In [45]:
ohr = [one_hot(words, voc_size)for words in sent]
print(ohr)

[[3782, 3302, 3439, 1096, 4748, 1047], [3151, 1278, 3439, 1557, 452, 2000], [2023, 740, 206, 4377], [3782, 34, 3439, 713, 3782, 4912], [2952, 3977, 3737, 3439, 1557, 452, 2000], [601, 3439, 1557, 452, 1262, 2091]]


In [47]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [53]:
## pre padding
sent_length=8
embedded_docs=pad_sequences(ohr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0 3782 3302 3439 1096 4748 1047]
 [   0    0 3151 1278 3439 1557  452 2000]
 [   0    0    0    0 2023  740  206 4377]
 [   0    0 3782   34 3439  713 3782 4912]
 [   0 2952 3977 3737 3439 1557  452 2000]
 [   0    0  601 3439 1557  452 1262 2091]]


In [55]:
## 10 feature dimesnions
dim=10

In [57]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

C:\Users\DELL\anaconda3\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [59]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)              │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [61]:
model.predict(embedded_docs[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 315ms/step


array([[ 0.04537373,  0.02498789, -0.0284113 ,  0.04314262, -0.02412645,
         0.03028561,  0.03401965,  0.02634095, -0.02884632,  0.03160918],
       [ 0.04537373,  0.02498789, -0.0284113 ,  0.04314262, -0.02412645,
         0.03028561,  0.03401965,  0.02634095, -0.02884632,  0.03160918],
       [ 0.00579467,  0.02023837, -0.01921433,  0.00028443, -0.0378545 ,
         0.0381079 , -0.04678915,  0.01556456, -0.04819679,  0.01782534],
       [-0.04572692,  0.01967324,  0.04665097, -0.04361726,  0.02614779,
        -0.0418685 ,  0.02807567,  0.02404394,  0.02191717,  0.00679244],
       [ 0.03243962, -0.04686737,  0.0005853 , -0.000418  ,  0.03791675,
         0.01640541, -0.0098206 , -0.04748831, -0.04574594, -0.04458332],
       [ 0.0382133 , -0.04693217, -0.01507857, -0.00316795, -0.00384407,
        -0.00444772,  0.01995535,  0.01982744, -0.00082716,  0.00383342],
       [-0.04876237, -0.0151539 , -0.03910098,  0.02331407,  0.02605737,
        -0.04685438, -0.00396105, -0.00387837

In [63]:
model.predict(embedded_docs)

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None